language: php

php:
  - 5.4
  - 5.5

services:
  - redis-server
  - elasticsearch

install:
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
  - composer self-update && composer --version
  - composer install

script:
  - php ./.test.php run --coverage-xml --quiet

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./tests/_log/coverage.xml
